module.exports = {

    profile1 : [
        {
            "mean":100,
            "sd" : 1
        },
        {
            "mean":125,
            "sd":3    
        },
        {
            "mean":130,
            "sd":5
        },
        {
            "mean":100,
            "sd":3.5
        },
        {
            "mean":195,
            "sd" : 3
        },
        {
            "mean":200,
            "sd":2    
        },
        {
            "mean":210,
            "sd":4.5
        },
        {
            "mean":315,
            "sd":2
        },
        {
            "mean":330,
            "sd" : 2.3
        },
        {
            "mean":345,
            "sd":3    
        },
        {
            "mean":400,
            "sd":2
        },
        {
            "mean":410,
            "sd":3.5
        },
        {
            "mean":365,
            "sd" : 3
        },
        {
            "mean":200,
            "sd":2    
        },
        {
            "mean":175,
            "sd":3
        },
        {
            "mean":100,
            "sd":1
        },
        {
            "mean":100,
            "sd" : 1
        },
        {
            "mean":125,
            "sd":3    
        },
        {
            "mean":130,
            "sd":5
        },
        {
            "mean":100,
            "sd":3.5
        },
        {
            "mean":195,
            "sd" : 3
        },
        {
            "mean":200,
            "sd":2    
        },
        {
            "mean":210,
            "sd":4.5
        },
        {
            "mean":315,
            "sd":2
        },
        {
            "mean":330,
            "sd" : 2.3
        },
        {
            "mean":345,
            "sd":3    
        },
        {
            "mean":400,
            "sd":2
        },
        {
            "mean":410,
            "sd":3.5
        },
        {
            "mean":365,
            "sd" : 3
        },
        {
            "mean":200,
            "sd":2    
        },
        {
            "mean":175,
            "sd":3
        },
        {
            "mean":100,
            "sd":1
        }
    ],

    profile2 : [

        {
            "mean":500,
            "sd" : 5
        },
        {
            "mean":600,
            "sd":3    
        },
        {
            "mean":700,
            "sd":6
        },
        {
            "mean":800,
            "sd":3.5
        },
        {
            "mean":900,
            "sd" : 4
        },
        {
            "mean":1000,
            "sd":2    
        },
        {
            "mean":1000,
            "sd":7
        },
        {
            "mean":800,
            "sd":2
        },
        {
            "mean":760,
            "sd" : 2.3
        },
        {
            "mean":900,
            "sd":3    
        },
        {
            "mean":600,
            "sd":2
        },
        {
            "mean":300,
            "sd":3.5
        },
        {
            "mean":245,
            "sd" : 3
        },
        {
            "mean":250,
            "sd":2    
        },
        {
            "mean":300,
            "sd":3
        },
        {
            "mean":500,
            "sd":1
        },
        {
            "mean":650,
            "sd" : 3
        },
        {
            "mean":730,
            "sd":3    
        },
        {
            "mean":815,
            "sd":5
        },
        {
            "mean":914,
            "sd":3.5
        },
        {
            "mean":945,
            "sd" : 3
        },
        {
            "mean":1015,
            "sd":2    
        },
        {
            "mean":1300,
            "sd":4.5
        },
        {
            "mean":1400,
            "sd":4
        },
        {
            "mean":1505,
            "sd" : 2.3
        },
        {
            "mean":1348,
            "sd":3    
        },
        {
            "mean":1452,
            "sd":2
        },
        {
            "mean":1410,
            "sd":3.5
        },
        {
            "mean":1245,
            "sd" : 3
        },
        {
            "mean":1103,
            "sd":2    
        },
        {
            "mean":1056,
            "sd":3
        },
        {
            "mean":1000,
            "sd":1
        }

    ]
}