module.exports = {

    litersProfile : [
        {
            "mean":100,
            "sd" : 5
        },
        {
            "mean":110,
            "sd":2    
        },
        {
            "mean":130,
            "sd":2
        },
        {
            "mean":150,
            "sd":2
        },
        {
            "mean":125,
            "sd" : 5
        },
        {
            "mean":100,
            "sd":5    
        },
        {
            "mean":150,
            "sd":1
        },
        {
            "mean":165,
            "sd":2
        },
        {
            "mean":170,
            "sd" : 3
        },
        {
            "mean":190,
            "sd":2    
        },
        {
            "mean":200,
            "sd":3
        },
        {
            "mean":175,
            "sd":5
        },
        {
            "mean":130,
            "sd" : 3
        },
        {
            "mean":125,
            "sd":5    
        },
        {
            "mean":100,
            "sd":2
        },
        {
            "mean":75,
            "sd":2.5
        },
        {
            "mean":55,
            "sd" : 3
        },
        {
            "mean":65,
            "sd":5    
        },
        {
            "mean":25,
            "sd":1
        },
        {
            "mean":34,
            "sd":1
        },
        {
            "mean":55,
            "sd" : 3
        },
        {
            "mean":65,
            "sd":5    
        },
        {
            "mean":25,
            "sd":1
        },
        {
            "mean":34,
            "sd":1
        },
        {
            "mean":65,
            "sd":5    
        },
        {
            "mean":25,
            "sd":1
        },
        {
            "mean":34,
            "sd":1
        }
    ],

    phProfile : [
        {
            "mean":10,
            "sd" : 0.4
        },
        {
            "mean":9,
            "sd":0.25    
        },
        {
            "mean":6,
            "sd":0.25
        },
        {
            "mean":7,
            "sd":0.1
        },
        {
            "mean":10,
            "sd" : 0.4
        },
        {
            "mean":9,
            "sd":0.25    
        },
        {
            "mean":6,
            "sd":0.25
        },
        {
            "mean":7,
            "sd":0.1
        },
        {
            "mean":10,
            "sd" : 0.4
        },
        {
            "mean":9,
            "sd":0.25    
        },
        {
            "mean":6,
            "sd":0.25
        },
        {
            "mean":7,
            "sd":0.1
        },
        {
            "mean":10,
            "sd" : 0.4
        },
        {
            "mean":9,
            "sd":0.25    
        },
        {
            "mean":6,
            "sd":0.25
        },
        {
            "mean":7,
            "sd":0.1
        },
        {
            "mean":10,
            "sd" : 0.4
        },
        {
            "mean":9,
            "sd":0.25    
        },
        {
            "mean":6,
            "sd":0.25
        },
        {
            "mean":7,
            "sd":0.1
        },
        {
            "mean":10,
            "sd" : 0.4
        },
        {
            "mean":9,
            "sd":0.25    
        },
        {
            "mean":6,
            "sd":0.25
        },
        {
            "mean":7,
            "sd":0.1
        },
        {
            "mean":6,
            "sd":0.25
        },
        {
            "mean":7,
            "sd":0.1
        },
        {
            "mean":10,
            "sd" : 0.4
        }
    ]
}